#ifndef NRFX_CONFIG_H__
#define NRFX_CONFIG_H__

#define NRFX_POWER_ENABLED   1
#define NRFX_POWER_DEFAULT_CONFIG_IRQ_PRIORITY  7

#define NRFX_CLOCK_ENABLED   0

#define NRFX_UARTE_ENABLED   1
#define NRFX_UARTE0_ENABLED  1

#define NRFX_UARTE1_ENABLED  0
#define NRFX_UARTE2_ENABLED  0
#define NRFX_UARTE3_ENABLED  0

#define NRFX_TIMER_ENABLED 1
#define NRFX_TIMER3_ENABLED 1
#define NRFX_TIMER_DEFAULT_CONFIG_IRQ_PRIORITY 6

#define NRFX_PRS_ENABLED     0

#endif // NRFX_CONFIG_H__
