#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

#define NRFX_TIMER_ENABLED 1
#define NRFX_TIMER0_ENABLED 1
#define NRFX_TIMER_DEFAULT_CONFIG_FREQUENCY 0
#define NRFX_TIMER_DEFAULT_CONFIG_MODE 0
#define NRFX_TIMER_DEFAULT_CONFIG_IRQ_PRIORITY 6
#define NRFX_TIMER_DEFAULT_CONFIG_BIT_WIDTH 0

#define NRF_LOG_ENABLED 0

#endif // #ifndef SDK_CONFIG_H
